export const commands = {
  commandAPM: true,
  commandAghs: true,
  commandAvg: true,
  commandBeta: true,
  commandBuilds: true,
  commandCommands: true,
  commandCount: false,
  commandDelay: true,
  commandDisable: false,
  commandDotabod: true,
  commandDotabuff: true,
  commandFixdbl: true,
  commandFixparty: true,
  commandFriends: false,
  commandGM: true,
  commandGPM: true,
  commandGeo: true,
  commandHero: true,
  commandInnate: true,
  commandItems: true,
  commandLG: true,
  commandLGS: true,
  commandLastFm: false,
  commandLocale: true,
  commandLost: true,
  commandMatch: true,
  commandMmr: true,
  commandModsonly: true,
  commandMute: true,
  commandNP: true,
  commandOnline: true,
  commandOnly: true,
  commandOpendota: true,
  commandPing: true,
  commandPleb: true,
  commandProfile: true,
  commandRanked: true,
  commandRecent: true,
  commandRefresh: true,
  commandResetwl: true,
  commandRosh: true,
  commandSetdelay: true,
  commandSetmmr: true,
  commandShard: true,
  commandSmurfs: true,
  commandSpectators: true,
  commandStats: true,
  commandSteam: true,
  commandStreamers: true,
  commandTest: false,
  commandToday: true,
  commandUnresolved: true,
  commandVersion: true,
  commandWL: true,
  commandWinProbability: true,
  commandWon: true,
  commandXPM: true,
}
export type CommandKeys = keyof typeof commands

export const defaultSettings = {
  obsServerPassword: '',
  obsServerPort: 4455,
  aegis: true,
  bets: true,
  betsInfo: {
    duration: 4 * 60,
    no: 'No',
    title: 'Will we win with [heroname]?',
    yes: 'Yes',
  },
  battlepass: false,
  chatter: true,
  chatters: {
    bounties: {
      enabled: true,
    },
    commandsReady: {
      enabled: true,
    },
    dotapatch: {
      enabled: true,
    },
    firstBloodDeath: {
      enabled: true,
    },
    killstreak: {
      enabled: true,
    },
    matchOutcome: {
      enabled: true,
    },
    midas: {
      enabled: true,
    },
    neutralItems: {
      enabled: false,
    },
    noTp: {
      enabled: true,
    },
    passiveDeath: {
      enabled: true,
    },
    pause: {
      enabled: true,
    },
    powerTreads: {
      enabled: true,
    },
    roshDeny: {
      enabled: true,
    },
    roshPickup: {
      enabled: true,
    },
    roshanKilled: {
      enabled: true,
    },
    smoke: {
      enabled: true,
    },
    tip: {
      enabled: true,
    },
  },
  customMmr: '[currentmmr] | [currentrank] | Next rank at [nextmmr] [wins]',
  'minimap-blocker': true,
  minimapRight: false,
  mmr: null,
  'mmr-tracker': true,
  'obs-scene-switcher': true,
  'obs-dc': '[dotabod] game disconnected',
  'obs-minimap': '[dotabod] blocking minimap',
  'obs-picks': '[dotabod] blocking picks',
  'only-block-ranked': true,
  'picks-blocker': true,
  rosh: true,
  'minimap-simple': false,
  'minimap-xl': false,
  'minimap-opacity': 0.7,
  onlyParty: false,
  livePolls: true,
  streamDelay: 0,
  showRankMmr: true,
  showRankImage: true,
  showRankLeader: true,
  notablePlayersOverlay: true,
  notablePlayersOverlayFlags: true,
  notablePlayersOverlayFlagsCmd: true,
  streamersNpSuffix: false,
  streamersAnnounce: false,
  winProbabilityOverlay: false,
  winProbabilityOverlayIntervalMinutes: 5,
  tellChatNewMMR: true,
  tellChatBets: true,
  queueBlocker: false,
  queueBlockerFindMatch: false,
  queueBlockerFindMatchText: 'Ranked match / All pick / Europe East, Russia',
  lastFmOverlay: false,
  lastFmUsername: '',
  lastFmRefreshRate: 30, // In seconds
  disableAutoClipping: false,
  autoTranslate: false,
  translationLanguage: 'en',
  translateOnOverlay: false,
  crypto_payment_interest: {
    interested: false,
    tier: 'PRO',
    transactionType: 'RECURRING',
  },
  rankOnly: {
    enabled: false,
    minimumRank: 'Herald',
    minimumRankTier: 0,
  },
  discardZeroBets: false,
  // Master switch: when on (default), features released after a streamer's last
  // visit are enabled by default. Per-feature toggles (e.g. cosmeticsAnnounce)
  // override this once explicitly set.
  autoOptInNewFeatures: true,
  // New-feature toggle for cosmetic-set announcements. null = follow
  // autoOptInNewFeatures; true/false = explicit streamer choice (always wins).
  cosmeticsAnnounce: null as boolean | null,
  ...commands,
  autoCommandsOnMatchStart: [],
}

export type SettingKeys = keyof typeof defaultSettings
export const Settings = Object.fromEntries(
  Object.keys(defaultSettings).map((key) => [key, key]),
) as { [K in SettingKeys]: K }
