import type { defaultSettings } from '@/lib/defaultSettings'

type Settings = typeof defaultSettings

export interface SettingMetadata {
  key: string
  label: string
  description: string
  searchTerms: string[]
  category:
    | 'obs'
    | 'overlay'
    | 'chat'
    | 'stream'
    | 'mmr'
    | 'bets'
    | 'commands'
    | 'display'
    | 'advanced'
  page: {
    path: string
    section?: string
  }
  isNested?: boolean
  parentKey?: keyof Settings
}

export const settingsMetadata: SettingMetadata[] = [
  // OBS Settings
  {
    category: 'obs',
    description: 'Password for OBS WebSocket connection',
    key: 'obsServerPassword',
    label: 'OBS Server Password',
    page: { path: '/dashboard', section: 'obs-setup' },
    searchTerms: ['obs', 'password', 'websocket', 'connection'],
  },
  {
    category: 'obs',
    description: 'Port number for OBS WebSocket connection',
    key: 'obsServerPort',
    label: 'OBS Server Port',
    page: { path: '/dashboard', section: 'obs-setup' },
    searchTerms: ['obs', 'port', 'websocket', 'connection'],
  },
  {
    category: 'obs',
    description: 'URL for OBS WebSocket connection',
    key: 'obsServerUrl',
    label: 'OBS Server URL',
    page: { path: '/dashboard', section: 'obs-setup' },
    searchTerms: ['obs', 'url', 'websocket', 'connection', 'address'],
  },

  // Stream Settings
  {
    category: 'stream',
    description: 'Delay in seconds between game and stream',
    key: 'streamDelay',
    label: 'Stream Delay',
    page: { path: '/dashboard/features', section: 'stream-delay' },
    searchTerms: ['stream', 'delay', 'latency', 'offset'],
  },
  {
    category: 'display',
    description: 'Language for bot messages and responses',
    key: 'locale',
    label: 'Language',
    page: { path: '/dashboard/features', section: 'language' },
    searchTerms: ['language', 'locale', 'translation', 'internationalization', 'i18n'],
  },

  // MMR Settings
  {
    category: 'mmr',
    description: 'Track and display MMR changes',
    key: 'mmr-tracker',
    label: 'MMR Tracker',
    page: { path: '/dashboard/features', section: 'mmr-tracker' },
    searchTerms: ['mmr', 'tracker', 'rating', 'rank', 'elo'],
  },
  {
    category: 'mmr',
    description: 'Override MMR with custom value',
    key: 'customMmr',
    label: 'Custom MMR',
    page: { path: '/dashboard/features', section: 'mmr-tracker' },
    searchTerms: ['custom', 'mmr', 'override', 'manual', 'rating'],
  },
  {
    category: 'display',
    description: 'Display MMR alongside rank',
    key: 'showRankMmr',
    label: 'Show Rank MMR',
    page: { path: '/dashboard/features', section: 'rank-only' },
    searchTerms: ['show', 'rank', 'mmr', 'display', 'rating'],
  },
  {
    category: 'display',
    description: 'Display rank medal image',
    key: 'showRankImage',
    label: 'Show Rank Image',
    page: { path: '/dashboard/features', section: 'rank-only' },
    searchTerms: ['show', 'rank', 'image', 'medal', 'badge', 'icon'],
  },
  {
    category: 'display',
    description: 'Display leaderboard ranking',
    key: 'showRankLeader',
    label: 'Show Rank Leader',
    page: { path: '/dashboard/features', section: 'rank-only' },
    searchTerms: ['show', 'rank', 'leader', 'leaderboard', 'top'],
  },

  // Overlay Features
  {
    category: 'overlay',
    description: 'Display Aegis expiration timer',
    key: 'aegis',
    label: 'Aegis Timer',
    page: { path: '/dashboard/features/overlay', section: 'aegis' },
    searchTerms: ['aegis', 'timer', 'roshan', 'expiration'],
  },
  {
    category: 'overlay',
    description: 'Track Roshan respawn timer',
    key: 'rosh',
    label: 'Roshan Timer',
    page: { path: '/dashboard/features/overlay', section: 'rosh' },
    searchTerms: ['roshan', 'rosh', 'timer', 'respawn'],
  },
  {
    category: 'overlay',
    description: 'Hide minimap to prevent stream sniping',
    key: 'minimap-blocker',
    label: 'Minimap Blocker',
    page: { path: '/dashboard/features/overlay', section: 'minimap' },
    searchTerms: ['minimap', 'blocker', 'hide', 'stream', 'snipe', 'anti-snipe'],
  },
  {
    category: 'overlay',
    description: 'Use simple minimap blocking style',
    key: 'simple-blocker',
    label: 'Simple Minimap Blocker',
    page: { path: '/dashboard/features/overlay', section: 'minimap' },
    searchTerms: ['simple', 'minimap', 'blocker', 'style'],
  },
  {
    category: 'overlay',
    description: 'Use extra large minimap size',
    key: 'xl-minimap',
    label: 'XL Minimap',
    page: { path: '/dashboard/features/overlay', section: 'minimap' },
    searchTerms: ['xl', 'minimap', 'large', 'size', 'big'],
  },
  {
    category: 'overlay',
    description: 'Hide hero picks during draft',
    key: 'picks-blocker',
    label: 'Picks Blocker',
    page: { path: '/dashboard/features/overlay', section: 'picks' },
    searchTerms: ['picks', 'blocker', 'draft', 'hide', 'heroes'],
  },
  {
    category: 'overlay',
    description: 'Display win/loss record',
    key: 'wl',
    label: 'Win/Loss Overlay',
    page: { path: '/dashboard/features/overlay', section: 'wl' },
    searchTerms: ['win', 'loss', 'wl', 'record', 'stats'],
  },
  {
    category: 'overlay',
    description: 'Display current MMR on stream',
    key: 'mmr-overlay',
    label: 'MMR Overlay',
    page: { path: '/dashboard/features/overlay', section: 'mmr-overlay' },
    searchTerms: ['mmr', 'overlay', 'rating', 'display'],
  },
  {
    category: 'overlay',
    description: 'Show real-time win probability',
    key: 'win-probability',
    label: 'Win Probability',
    page: { path: '/dashboard/features/overlay', section: 'win-probability' },
    searchTerms: ['win', 'probability', 'chance', 'prediction'],
  },
  {
    category: 'overlay',
    description: 'Display Twitch polls on stream',
    key: 'poll-overlay',
    label: 'Poll Overlay',
    page: { path: '/dashboard/features/overlay', section: 'poll-overlay' },
    searchTerms: ['poll', 'overlay', 'voting', 'twitch'],
  },

  // Bets
  {
    category: 'bets',
    description: 'Enable Twitch prediction betting',
    key: 'bets',
    label: 'Betting System',
    page: { path: '/dashboard/features', section: 'bets' },
    searchTerms: ['bets', 'betting', 'predictions', 'gamble', 'wager'],
  },
  {
    category: 'bets',
    description: 'Only create bets for party games',
    isNested: true,
    key: 'betsInfo.onlyParty',
    label: 'Party Bets Only',
    page: { path: '/dashboard/features', section: 'bets' },
    parentKey: 'betsInfo',
    searchTerms: ['party', 'bets', 'only', 'team'],
  },

  // Chat Features
  {
    category: 'chat',
    description: 'Enable automatic chat messages',
    key: 'chatter',
    label: 'Chat Bot',
    page: { path: '/dashboard/features/chat', section: 'chatter' },
    searchTerms: ['chat', 'bot', 'chatter', 'automatic', 'messages'],
  },
  {
    category: 'chat',
    description: 'Announce Midas purchase timing',
    isNested: true,
    key: 'chatters.midas',
    label: 'Midas Timer',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['midas', 'timer', 'chat', 'item', 'gold'],
  },
  {
    category: 'chat',
    description: 'Announce when game is paused',
    isNested: true,
    key: 'chatters.pause',
    label: 'Pause Announcements',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['pause', 'chat', 'announcement', 'game'],
  },
  {
    category: 'chat',
    description: 'Alert when enemies smoke',
    isNested: true,
    key: 'chatters.smoke',
    label: 'Smoke Gank Alert',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['smoke', 'gank', 'alert', 'enemy', 'warning'],
  },
  {
    category: 'chat',
    description: 'Announce when your team activates Smoke of Deceit, and rib you if you missed it',
    isNested: true,
    key: 'chatters.smokeActivated',
    label: 'Smoke Activated Alert',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['smoke', 'gank', 'deceit', 'activated', 'team'],
  },
  {
    category: 'chat',
    description: 'Announce Aegis pickup',
    isNested: true,
    key: 'chatters.aegis-pickup',
    label: 'Aegis Pickup',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['aegis', 'pickup', 'roshan', 'chat'],
  },
  {
    category: 'chat',
    description: 'React to tips in game',
    isNested: true,
    key: 'chatters.tip',
    label: 'Tip Messages',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['tip', 'chat', 'reaction', 'message'],
  },
  {
    category: 'chat',
    description: 'Announce special rune pickups',
    isNested: true,
    key: 'chatters.rune-pickup',
    label: 'Rune Pickup',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['rune', 'pickup', 'chat', 'power'],
  },
  {
    category: 'chat',
    description: 'Announce first blood',
    isNested: true,
    key: 'chatters.firstblood',
    label: 'First Blood',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['first', 'blood', 'kill', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce kill streaks',
    isNested: true,
    key: 'chatters.killstreak',
    label: 'Kill Streaks',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['kill', 'streak', 'rampage', 'ultra', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce match results',
    isNested: true,
    key: 'chatters.matchOutcome',
    label: 'Match Outcome',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['match', 'outcome', 'win', 'loss', 'result', 'chat'],
  },
  {
    category: 'chat',
    description: 'Welcome message when spectating',
    isNested: true,
    key: 'chatters.spectatorWelcome',
    label: 'Spectator Welcome',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['spectator', 'welcome', 'watching', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce Roshan kills',
    isNested: true,
    key: 'chatters.roshanKilled',
    label: 'Roshan Killed',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['roshan', 'killed', 'rosh', 'chat'],
  },
  {
    category: 'advanced',
    description:
      'Automatically enable new dotabod features (chat, overlay, and more) as they launch',
    key: 'autoOptInNewFeatures',
    label: 'Auto-enable new features',
    page: { path: '/dashboard/features', section: 'new-features' },
    searchTerms: ['new', 'features', 'auto', 'opt in', 'updates', 'beta'],
  },
  {
    category: 'chat',
    description:
      "Announce your hero's captured cosmetic set in chat with a link to your collection",
    key: 'cosmeticsAnnounce',
    label: 'Cosmetic Set Announcements',
    page: { path: '/dashboard/whats-new', section: 'cosmetics' },
    searchTerms: ['cosmetic', 'set', 'loadout', 'items', 'hero', 'chat', 'new features'],
  },
  {
    category: 'chat',
    description: 'Announce deaths with passive items unused',
    isNested: true,
    key: 'chatters.passiveDeath',
    label: 'Passive Death',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['passive', 'death', 'faerie', 'fire', 'stick', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce when aegis is picked up',
    isNested: true,
    key: 'chatters.roshPickup',
    label: 'Aegis Pickup',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['aegis', 'pickup', 'roshan', 'rosh', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce when aegis is denied',
    isNested: true,
    key: 'chatters.roshDeny',
    label: 'Aegis Deny',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['aegis', 'deny', 'roshan', 'rosh', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce bounty rune pickups',
    isNested: true,
    key: 'chatters.bounties',
    label: 'Bounty Runes',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['bounty', 'runes', 'gold', 'chat'],
  },
  {
    category: 'chat',
    description: 'Track power treads toggling stats',
    isNested: true,
    key: 'chatters.powerTreads',
    label: 'Power Treads Toggle',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['power', 'treads', 'toggle', 'mana', 'save', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce when you give first blood',
    isNested: true,
    key: 'chatters.firstBloodDeath',
    label: 'First Blood Death',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['first', 'blood', 'death', 'give', 'chat'],
  },
  {
    category: 'chat',
    description: 'Alert when you dont have a TP scroll',
    isNested: true,
    key: 'chatters.noTp',
    label: 'No TP Alert',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['no', 'tp', 'scroll', 'teleport', 'missing', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce when match commands are available',
    isNested: true,
    key: 'chatters.commandsReady',
    label: 'Commands Ready',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['commands', 'ready', 'match', 'data', 'found', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce when neutral item tiers become available',
    isNested: true,
    key: 'chatters.neutralItems',
    label: 'Neutral Items',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['neutral', 'items', 'tier', 'available', 'jungle', 'chat'],
  },
  {
    category: 'chat',
    description: 'Announce new Dota 2 patches',
    isNested: true,
    key: 'chatters.dotapatch',
    label: 'Dota Patch',
    page: { path: '/dashboard/features/chat', section: 'chatters' },
    parentKey: 'chatters',
    searchTerms: ['dota', 'patch', 'update', 'new', 'version', 'chat'],
  },

  // Commands
  {
    category: 'commands',
    description: 'Show actions per minute',
    key: 'commandAPM',
    label: '!apm Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['apm', 'command', 'actions', 'minute'],
  },
  {
    category: 'commands',
    description: 'Show average stats',
    key: 'commandAvg',
    label: '!avg Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['avg', 'average', 'command', 'stats'],
  },
  {
    category: 'commands',
    description: 'List available commands',
    key: 'commandCommands',
    label: '!commands Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['commands', 'list', 'help'],
  },
  {
    category: 'commands',
    description: 'Show stream delay',
    key: 'commandDelay',
    label: '!delay Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['delay', 'command', 'stream'],
  },
  {
    category: 'commands',
    description: 'Link to Dotabuff profile',
    key: 'commandDotabuff',
    label: '!dotabuff Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['dotabuff', 'command', 'profile', 'link'],
  },
  {
    category: 'commands',
    description: 'Show current game mode',
    key: 'commandGameMode',
    label: '!gamemode Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['gamemode', 'mode', 'command'],
  },
  {
    category: 'commands',
    description: 'Show gold per minute',
    key: 'commandGPM',
    label: '!gpm Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['gpm', 'gold', 'minute', 'command'],
  },
  {
    category: 'commands',
    description: 'Show hero information',
    key: 'commandHero',
    label: '!hero Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['hero', 'command', 'character'],
  },
  {
    category: 'commands',
    description: 'Show last game stats',
    key: 'commandLG',
    label: '!lg Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['lg', 'last', 'game', 'command'],
  },
  {
    category: 'commands',
    description: 'Show current match ID',
    key: 'commandMatchId',
    label: '!matchid Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['matchid', 'match', 'id', 'command'],
  },
  {
    category: 'commands',
    description: 'Show current MMR',
    key: 'commandMmr',
    label: '!mmr Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['mmr', 'rating', 'rank', 'command'],
  },
  {
    category: 'commands',
    description: 'List channel moderators',
    key: 'commandModList',
    label: '!modlist Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['modlist', 'mods', 'moderators', 'command'],
  },
  {
    category: 'commands',
    description: 'Show notable players',
    key: 'commandNP',
    label: '!np Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['np', 'notable', 'players', 'command'],
  },
  {
    category: 'commands',
    description: 'Link to OpenDota profile',
    key: 'commandOpendota',
    label: '!opendota Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['opendota', 'profile', 'link', 'command'],
  },
  {
    category: 'commands',
    description: 'Test bot response',
    key: 'commandPing',
    label: '!ping Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['ping', 'test', 'command'],
  },
  {
    category: 'commands',
    description: 'Show hero winrate',
    key: 'commandWinrate',
    label: '!winrate Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['winrate', 'win', 'rate', 'command'],
  },
  {
    category: 'commands',
    description: 'Show experience per minute',
    key: 'commandXPM',
    label: '!xpm Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['xpm', 'experience', 'minute', 'command'],
  },
  {
    category: 'commands',
    description: 'Show Steam profile link',
    key: 'commandSteam',
    label: '!steam Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['steam', 'profile', 'link', 'command'],
  },
  {
    category: 'commands',
    description: 'Show win/loss record',
    key: 'commandWL',
    label: '!wl Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['wl', 'win', 'loss', 'record', 'command'],
  },
  {
    category: 'commands',
    description: 'Toggle Dotabod on/off (mod only)',
    key: 'commandDisable',
    label: '!toggle Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['toggle', 'disable', 'enable', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Force online/offline status (mod only)',
    key: 'commandOnline',
    label: '!online Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['online', 'offline', 'status', 'force', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Mute auto chatters but keep commands (mod only)',
    key: 'commandMute',
    label: '!mute Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['mute', 'unmute', 'chatters', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Fix MMR for party matches (mod only)',
    key: 'commandFixparty',
    label: '!fixparty Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['fixparty', 'fixsolo', 'mmr', 'party', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Refresh OBS overlay (mod only)',
    key: 'commandRefresh',
    label: '!refresh Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['refresh', 'overlay', 'obs', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Manually set MMR (mod only)',
    key: 'commandSetmmr',
    label: '!setmmr Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['setmmr', 'mmr', 'set', 'manual', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Join/leave beta testing (mod only)',
    key: 'commandBeta',
    label: '!beta Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['beta', 'testing', 'features', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Check if current match is ranked',
    key: 'commandRanked',
    label: '!ranked Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['ranked', 'isranked', 'match', 'type', 'command'],
  },
  {
    category: 'commands',
    description: 'Show lifetime games for all players',
    key: 'commandSmurfs',
    label: '!smurfs Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['smurfs', 'lifetimes', 'games', 'totals', 'players', 'command'],
  },
  {
    category: 'commands',
    description: 'Show game medals/ranks for all players',
    key: 'commandGM',
    label: '!gm Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['gm', 'medals', 'ranks', 'players', 'command'],
  },
  {
    category: 'commands',
    description: 'Information about Dotabod',
    key: 'commandDotabod',
    label: '!dotabod Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['dotabod', 'about', 'info', 'bot', 'command'],
  },
  {
    category: 'commands',
    description: 'Show last game score and duration',
    key: 'commandLGS',
    label: '!lgs Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['lgs', 'lastgamescore', 'last', 'game', 'score', 'command'],
  },
  {
    category: 'commands',
    description: 'Show profile for specific player color',
    key: 'commandProfile',
    label: '!profile Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['profile', 'stats', 'check', 'player', 'color', 'command'],
  },
  {
    category: 'commands',
    description: 'Get pro builds for current hero',
    key: 'commandBuilds',
    label: '!builds Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['builds', 'build', 'pro', 'dota2pt', 'guide', 'command'],
  },
  {
    category: 'commands',
    description: 'Show Roshan and aegis status',
    key: 'commandRosh',
    label: '!rosh Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['rosh', 'roshan', 'aegis', 'timer', 'status', 'command'],
  },
  {
    category: 'commands',
    description: 'Show items for specific hero',
    key: 'commandItems',
    label: '!items Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['items', 'item', 'inventory', 'hero', 'equipment', 'command'],
  },
  {
    category: 'commands',
    description: 'Show current Dotabod version',
    key: 'commandVersion',
    label: '!version Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['version', 'update', 'current', 'build', 'command'],
  },
  {
    category: 'commands',
    description: 'Reset win/loss record (mod only)',
    key: 'commandResetwl',
    label: '!resetwl Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['resetwl', 'reset', 'win', 'loss', 'record', 'command', 'mod'],
  },
  {
    category: 'commands',
    description: 'Show current language/locale',
    key: 'commandLocale',
    label: '!locale Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['locale', 'language', 'translation', 'translatedby', 'command'],
  },
  {
    category: 'commands',
    description: 'Show current win probability',
    key: 'commandWinProbability',
    label: '!wp Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['wp', 'win', 'probability', 'chance', 'prediction', 'command'],
  },
  {
    category: 'commands',
    description: 'Show number of spectators watching',
    key: 'commandSpectators',
    label: '!spectators Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['spectators', 'viewers', 'watching', 'live', 'command'],
  },
  {
    category: 'commands',
    description: 'Show hero innate ability information',
    key: 'commandInnate',
    label: '!innate Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['innate', 'ability', 'passive', 'hero', 'skill', 'command'],
  },
  {
    category: 'commands',
    description: 'Show Aghanims Shard upgrade information',
    key: 'commandShard',
    label: '!shard Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['shard', 'aghanims', 'upgrade', 'hero', 'ability', 'command'],
  },
  {
    category: 'commands',
    description: 'Show Aghanims Scepter upgrade information',
    key: 'commandAghs',
    label: '!aghs Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['aghs', 'aghanims', 'scepter', 'upgrade', 'hero', 'ability', 'command'],
  },
  {
    category: 'commands',
    description: 'Show currently playing music from Last.fm',
    key: 'commandLastFm',
    label: '!song Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['song', 'music', 'lastfm', 'playing', 'track', 'command'],
  },
  {
    category: 'commands',
    description: 'Enable verified mode for specific ranks (mod only)',
    key: 'commandOnly',
    label: '!only Command',
    page: { path: '/dashboard/commands', section: 'commands' },
    searchTerms: ['only', 'verified', 'mode', 'rank', 'restriction', 'command', 'mod'],
  },

  // Advanced Features
  {
    category: 'overlay',
    description: 'Hide queue timer and information',
    key: 'queueBlocker',
    label: 'Queue Blocker',
    page: { path: '/dashboard/features/overlay', section: 'queue-blocker' },
    searchTerms: ['queue', 'blocker', 'hide', 'timer', 'matchmaking'],
  },
  {
    category: 'advanced',
    description: 'Turn off automatic Twitch clips',
    key: 'disableAutoClipping',
    label: 'Disable Auto Clipping',
    page: { path: '/dashboard/features/advanced', section: 'clipping' },
    searchTerms: ['disable', 'auto', 'clip', 'clipping', 'twitch'],
  },
  {
    category: 'advanced',
    description: 'Automatically switch OBS scenes',
    key: 'sceneSwitch',
    label: 'Scene Switcher',
    page: { path: '/dashboard/features/advanced', section: 'scene-switcher' },
    searchTerms: ['scene', 'switch', 'switcher', 'obs', 'automatic'],
  },

  // Notable Players
  {
    category: 'overlay',
    description: 'Track and announce notable players in games',
    key: 'notablePlayers',
    label: 'Notable Players',
    page: { path: '/dashboard/features/overlay', section: 'notable-players' },
    searchTerms: ['notable', 'players', 'pros', 'famous', 'track'],
  },
]

// Helper function to get all searchable text for a setting
export function getSearchableText(setting: SettingMetadata): string {
  return [setting.label, setting.description, ...setting.searchTerms, setting.key]
    .join(' ')
    .toLowerCase()
}

// Helper function to get setting by key
// Helper function to get settings by category
// Helper function to get settings by page
