import * as z from 'zod'
import { canAccessFeature, type SubscriptionRow } from '@/utils/subscription'

// Define schemas for each specific setting
const settingsSchema = {
  aegis: z.boolean(),
  autoCommandsOnMatchStart: z.array(z.string().max(45)),
  autoTranslate: z.boolean(),
  battlepass: z.boolean(),
  bets: z.boolean(),
  betsInfo: z.object({
    duration: z
      .string()
      .regex(/^\d+$/, 'Duration must be a numeric string')
      .transform((str) => Number.parseInt(str, 10))
      .refine((num) => num >= 30 && num <= 1800, {
        message: 'Duration must be between 30 and 1800 seconds',
      }),
    no: z.string().max(25),
    title: z.string().max(45),
    yes: z.string().max(25),
  }),
  chatter: z.boolean(),
  autoOptInNewFeatures: z.boolean(),
  // Tri-state: the null "follow autoOptInNewFeatures" state is the ABSENCE of a settings row
  // (the default), not a persisted value. The UI only ever PATCHes true/false, and Prisma Json
  // columns can't store raw null, so the write schema is boolean.
  cosmeticsAnnounce: z.boolean(),
  chatters: z
    .object({
      bounties: z.object({ enabled: z.boolean() }),
      commandsReady: z.object({ enabled: z.boolean() }),
      dotapatch: z.object({ enabled: z.boolean() }),
      firstBloodDeath: z.object({ enabled: z.boolean() }),
      killstreak: z.object({ enabled: z.boolean() }),
      matchOutcome: z.object({ enabled: z.boolean() }),
      midas: z.object({ enabled: z.boolean() }),
      neutralItems: z.object({ enabled: z.boolean() }),
      noTp: z.object({ enabled: z.boolean() }),
      passiveDeath: z.object({ enabled: z.boolean() }),
      pause: z.object({ enabled: z.boolean() }),
      powerTreads: z.object({ enabled: z.boolean() }),
      roshDeny: z.object({ enabled: z.boolean() }),
      roshPickup: z.object({ enabled: z.boolean() }),
      roshanKilled: z.object({ enabled: z.boolean() }),
      smoke: z.object({ enabled: z.boolean() }),
      tip: z.object({ enabled: z.boolean() }),
    })
    .partial(),
  commandAPM: z.boolean(),
  commandAghs: z.boolean(),
  commandAvg: z.boolean(),
  commandBuilds: z.boolean(),
  commandCommands: z.boolean(),
  commandDelay: z.boolean(),
  commandDisable: z.boolean(),
  commandDotabuff: z.boolean(),
  commandGM: z.boolean(),
  commandGPM: z.boolean(),
  commandHero: z.boolean(),
  commandInnate: z.boolean(),
  commandItems: z.boolean(),
  commandLG: z.boolean(),
  commandLGS: z.boolean(),
  commandLastFm: z.boolean(),
  commandLocale: z.boolean(),
  commandMmr: z.boolean(),
  commandModsonly: z.boolean(),
  commandNP: z.boolean(),
  commandOnline: z.boolean(),
  commandOnly: z.boolean(),
  commandOpendota: z.boolean(),
  commandPleb: z.boolean(),
  commandProfile: z.boolean(),
  commandRanked: z.boolean(),
  commandResetwl: z.boolean(),
  commandRosh: z.boolean(),
  commandShard: z.boolean(),
  commandSmurfs: z.boolean(),
  commandSpectators: z.boolean(),
  commandSteam: z.boolean(),
  commandVersion: z.boolean(),
  commandWL: z.boolean(),
  commandWinProbability: z.boolean(),
  commandXPM: z.boolean(),
  crypto_payment_interest: z.object({
    interested: z.boolean(),
    tier: z.enum(['FREE', 'PRO']),
    transactionType: z.enum(['RECURRING', 'LIFETIME']),
  }),
  disableAutoClipping: z.boolean(),
  discardZeroBets: z.boolean(),
  lastFmOverlay: z.boolean(),
  lastFmRefreshRate: z.number().min(5).max(60),
  lastFmUsername: z.string().max(45).optional(),
  livePolls: z.boolean(),
  'minimap-blocker': z.boolean(),
  'minimap-opacity': z.number().min(0).max(1),
  'minimap-simple': z.boolean(),
  'minimap-xl': z.boolean(),
  minimapRight: z.boolean(),
  mmr: z.number().min(0).max(30_000),
  'mmr-tracker': z.boolean(),
  notablePlayersOverlay: z.boolean(),
  notablePlayersOverlayFlags: z.boolean(),
  notablePlayersOverlayFlagsCmd: z.boolean(),
  'obs-dc': z.string().max(200).max(45),
  'obs-minimap': z.string().max(200).max(45),
  'obs-picks': z.string().max(200).max(45),
  'obs-scene-switcher': z.boolean(),
  obsServerPassword: z.string().max(45),
  obsServerPort: z.number().min(1).max(65_535),
  'only-block-ranked': z.boolean(),
  onlyParty: z.boolean(),
  'picks-blocker': z.boolean(),
  queueBlocker: z.boolean(),
  queueBlockerFindMatch: z.boolean(),
  queueBlockerFindMatchText: z.string().max(45),
  rankOnly: z.object({
    enabled: z.boolean(),
    minimumRank: z.enum([
      'Herald',
      'Guardian',
      'Crusader',
      'Archon',
      'Legend',
      'Ancient',
      'Divine',
      'Immortal',
    ]),
    minimumRankTier: z.number().min(0).max(100),
  }),
  rosh: z.boolean(),
  showRankImage: z.boolean(),
  showRankLeader: z.boolean(),
  showRankMmr: z.boolean(),
  streamDelay: z.number().min(0).max(3_000_000),
  tellChatBets: z.boolean(),
  tellChatNewMMR: z.boolean(),
  translateOnOverlay: z.boolean(),
  translationLanguage: z.string().max(5),
  winProbabilityOverlay: z.boolean(),
  winProbabilityOverlayIntervalMinutes: z.number().min(0).max(60),
}

type SettingKeys = keyof typeof settingsSchema
export const settingKeySchema = z.enum(
  Object.keys(settingsSchema) as [SettingKeys, ...SettingKeys[]],
)

// Add subscription validation to dynamic schema
export const dynamicSettingSchema = (
  key: SettingKeys,
  subscription: Partial<SubscriptionRow> | null,
) =>
  z
    .object({
      key: z.literal(key),
      value: settingsSchema[key],
    })
    .refine(() => canAccessFeature(key, subscription).hasAccess, {
      message: 'Your subscription tier does not have access to this feature',
    })

export const localePatchSchema = z.enum([
  'af-ZA',
  'ar-SA',
  'ca-ES',
  'cs-CZ',
  'da-DK',
  'de-DE',
  'el-GR',
  'es-ES',
  'fa-IR',
  'fi-FI',
  'fr-FR',
  'he-IL',
  'hu-HU',
  'it-IT',
  'ja-JP',
  'ko-KR',
  'nl-NL',
  'no-NO',
  'pl-PL',
  'pt-BR',
  'pt-PT',
  'ro-RO',
  'ru-RU',
  'sr-SP',
  'th-TH',
  'tl-PH',
  'sv-SE',
  'tr-TR',
  'uk-UA',
  'vi-VN',
  'zh-CN',
  'zh-TW',
  'en',
])
