nodeLinker: hoisted

publicHoistPattern:
  - '*prisma*'

overrides:
  '@voidzero-dev/vite-plus-test': npm:vitest@5.0.0
  vitest: 5.0.0

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  lefthook: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@5.0.0'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
